version: "2"
services:
  backend:
    depends_on:
      - db
    image: nadianb/foyer
    ports:
      - "8089:8089"
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"